version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/landing"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/console"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "daily"
