version: '3'
services:
  nginx:
    image: nginx:1.19
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  console-webui:
    build:
      context: ./console
      dockerfile: ./console/docker/Development.dockerfile
    command: nodemon --watch ./package.json --watch ./start.sh --exec ./start.sh
    working_dir: /app/console
    volumes:
      - ./console:/app/console
      - cache-yarn:/app/cache/yarn
    environment:
      - YARN_CACHE_FOLDER=/app/cache/yarn
      - AWANKU_API_URL=https://api.staging.awanku.xyz
  landing-webui:
    build:
      context: ./landing
      dockerfile: ./landing/docker/Development.dockerfile
    command: nodemon --watch ./package.json --watch ./start.sh --exec ./start.sh
    working_dir: /app/landing
    volumes:
      - ./landing:/app/landing
      - cache-yarn:/app/cache/yarn
    environment:
      - YARN_CACHE_FOLDER=/app/cache/yarn
      - AWANKU_API_URL=https://api.staging.awanku.xyz
volumes:
  cache-yarn:
