version: '3'
services:
  nginx:
    image: nginx:1.19
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  core-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: make run-dev
    working_dir: /app/backend
    stop_grace_period: 1s
    volumes:
      - ./backend:/app/backend
      - cache-go:/go
    environment:
      - DB_URL=postgres://postgres:secretpassword@db-main/awanku?sslmode=disable
  console-webui:
    build:
      context: ./console
      dockerfile: Dockerfile
    command: nodemon --watch ./package.json --watch ./start.sh --exec ./start.sh
    working_dir: /app/console
    volumes:
      - ./console:/app/console
      - cache-yarn:/app/cache/yarn
    environment:
      - YARN_CACHE_FOLDER=/app/cache/yarn
  landing-webui:
    build:
      context: ./landing
      dockerfile: Dockerfile
    command: nodemon --watch ./package.json --watch ./start.sh --exec ./start.sh
    working_dir: /app/landing
    volumes:
      - ./landing:/app/landing
      - cache-yarn:/app/cache/yarn
    environment:
      - YARN_CACHE_FOLDER=/app/cache/yarn
  db-main:
    image: postgres:12
    environment:
      - POSTGRES_DB=awanku
      - POSTGRES_PASSWORD=secretpassword
volumes:
  cache-yarn:
  cache-go:
