name: core-api

on:
  push:
    paths:
      - 'backend/**'
      - '.github/**'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/**'

jobs:
  test:
    runs-on: ubuntu-18.04
    services:
      maindb:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: awanku
          POSTGRES_PASSWORD: rahasia
          POSTGRES_DB: awanku
    env:
      ENVIRONMENT: test
      DATABASE_URL: postgres://awanku:rahasia@localhost:5432/awanku?sslmode=disable
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.x

    - name: Check out code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Run test suite
      working-directory: ./backend
      run: |
        go get -v -t -d ./...
        make test

  build:
    runs-on: ubuntu-18.04
    needs: [test]
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Build Docker image
        working-directory: ./backend
        run: |
          ./scripts/ci-docker-build.sh
